server:
  port: 7001

eureka:
  instance:
    hostname: eureka.server.7001.com # 定义主机名
    appname: Eureka-Server # 设置服务端实例名称，优先级高于 spring.application.name
    instance-id: eureka-server-instance2 # 设置实例 ID
  client:
    register-with-eureka: false # 默认为 true，设置 false 表示不向注册中心注册自己
    fetch-registry: false # 默认为 true，设置 false 表示不去注册中心 获取 注册信息
    # 指向集群中 其他的 注册中心
    service-url:
      defaultZone: http://eureka.server.7002.com:7002/eureka,http://eureka.server.7003.com:7003/eureka
