server:
  port: 8002

spring:
  application:
    name: eureka-client-producer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.26.184.41:3306/producer?useUnicode=true&characterEncoding=utf8

eureka:
  instance:
    appname: eureka-client-producer # 优先级比 spring.application.name 高
    instance-id: eureka-client-producer.instance1 # 设置当前实例 ID
    hostname: eureka.client.producer.8002 # 设置主机名
    lease-renewal-interval-in-seconds: 1 # 客户端向 注册中心 发送心跳的时间间隔，默认 30 秒
    lease-expiration-duration-in-seconds: 5 # 注册中心 等待心跳最长时间，超时剔除服务，默认 90 秒
  client:
    register-with-eureka: true # 默认为 true，注册到 注册中心
    fetch-registry: true # 默认为 true，从注册中心 获取 注册信息
    service-url:
      # 指向 注册中心 地址，注册到 集群所有的 注册中心。
      defaultZone: http://eureka.server.7001.com:7001/eureka,http://eureka.server.7002.com:7002/eureka,http://eureka.server.7003.com:7003/eureka
