server:
  port: 8008
spring:
  application:
    name: zookeeper-client-producer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.26.184.41:3306/producer?useUnicode=true&characterEncoding=utf8
  cloud:
    # zookeeper 配置
    zookeeper:
      # 配置连接 zookeeper 服务器的地址
      connect-string: 120.26.184.41:2181, 120.26.184.41:2182, 120.26.184.41:2183
