server:
  port: 9005

spring:
  application:
    name: consul-client-consumer
  cloud:
    # 配置 consul 信息
    consul:
      # 配置注册中心地址
      host: 120.26.184.41
      # 配置访问端口号
      port: 8500
      # 配置服务提供者信息(非必须配置)
      discovery:
        # 是否需要注册
        register: true
        # 配置实例 ID
        instance-id: ${spring.application.name}-${server.port}
        # 配置服务名
        service-name: ${spring.application.name}
        # 配置服务端口
        port: ${server.port}
        # 使用 ip 地址而非主机名
        prefer-ip-address: true
        # 设置健康检查路径
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        # 健康检查失败后，自动剔除服务（单位 s 表示秒，m 表示分钟）
        health-check-critical-timeout: 10s
management:
  endpoint:
    health:
      # 显示健康具体信息，默认不会显示详细信息
      show-details: always
